name: Update README Projects

on:
  schedule:
    - cron: '0 0 * * *' # Roda automaticamente todo dia à meia-noite
  workflow_dispatch: # Permite que você ative manualmente quando quiser

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3
      
      - name: Gerar lista de repositorios
        uses: richardtop/repo-list-generator@v1
        with:
          username: 'robson-lisboa'
